---
title: "Conclusions"
---

## Discussion/Synthesis
The study demonstrates the progression of early to moderate fibrosis in non alcoholic fatty livers is characterized by structural remodeling and fibrosis reinforcement pathways. A previous transcriptomic study by Wang et al. observed similar patterns of upregulation of the extracellular matrix pathways, resulting in hepatic stellate cell activation and excessive collagen deposition. Stellate cells activate the collagen production via ECM remodeling, changing the overall architecture of the liver (Wang 2022), which can be also supported by the findings of our enrichment pathway analyses. Our study also showed downregulation of metabolic and signaling pathways, suggesting a loss in normal liver cell functions, which can change the composition of the cells with the fibrosis advancements (Pantano 2021). 
A lot of studies done previously emphasize inflammation as the major, dominant factor of fibrosis progression, however, our findings indicate that ECM remodelling plays a much more significant role in the progression of fibrosis. When looking at past data and our results, it can be inferred that inflammation is a feature of the fibrosis disease, but structural reorganization is a more defining feature to distinguish the stages. Our study adds some new insight into fibrosis progression, showing that functional reprogramming of the liver can mark the stages more distinctly than signalling differences. By highlighting ECM driven remodelling as the defining molecular shift at these intermediate stages of the disease can help refine and distinguish NAFLD progression. 


## Limitations
There are several limitations to be considered when interpreting the results of the data. First, even though the sample size is relatively large, the general grouping of fibrosis stages as early and moderate may have masked some subtle, specific changes within each specific fibrosis stage. Second, the metadata given in the original dataset did not specify the different cell types used in the samples, which can change how each different gene was expressed and how the changes were driven. There was also the possibility of misleading results from the pathway enrichments. As pathway enrichment relies on preexisting gene annotations, some of the annotated functions have no biological relevance to livers due to overlapping genes in databases. Even though some statistical thresholds were applied, the small effects that are biologically meaningful may have been overlooked due to these limitations. 

## Future Directions
Future studies can build their analyses by following patients over a period of time, which could provide stronger evidence for gene relationships to fibrosis progression. More specific investigation of inflammation and insulin resistance pathways can also help with creating databases with more clarity and specificity in order to have a more successful and precise pathway enrichment analysis. The addition of understanding other functional changes in the liver can help find factors that relate to these changes. Understanding the differentially depressed genes can also help identify new therapies for fibrosis progression. 

